---
- hosts: all
  become: true

  pre_tasks:
    - name: Update repositories
      package:
        update_cache: true
      changed_when: false

- hosts: all
  become: true
  roles:
    - workstation
